title: Vivek
subtitle: A Jekyll Portfolio
description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
#     - text: Shop
#       url : /shop
    - text: Contact Me
      url : /contact
#     - text: Styleguide
#       url: /styleguide
#     - text: Get Started
#       url: /get-started

# Edit these details

author_logo: profile.png
author: VivekVinushanth
author_bio: Hey! This is Vivek, an undergraduate of Computer Science and Engineering, University of Moratuwa and was an intern at WSO2.Passionate, proactive and task-oriented person with creative abilities | Believes, determination, persistence and sacrifice lead to success | Livelong learner | Interested in designing solutions & architectures 
author_email: "vivekc.16@cse.mrt.ac.lk"
author_location: Colombo,Srilanka.
# author_website_url: "https://sujaykundu.com"
typewrite-text: devlopr is a jekyll theme built for developers. You can edit this in _config.yml file

author_work_experiences:
            - company_name: WSO2 
              company_logo: wso2.png
              company_url: https://wso2.com/
              designation: Software Engineering Intern (Identity Server Team)
              description: Worked on WSO2 Identity Server developing new feature CIBA
              visibility: true
#             - company_name: Microsoft
#               company_logo: microsoft.png
#               company_url: https://microsoft.com
#               designation: Azure Developer
#               description: Worked on various Azure Cloud Products
#               visibility: true

author_education_details:
              - college_logo: moratuwa.png
                college_name: University of Moratuwa
                college_url: https://uom.lk/
                college_degree: Bachelor of Science of Engineering (Hons)
                field: Computer Sciecne & Engineering
                visibility: true

author_project_details:
              - project_thumbnail: .png
                project_title: Unsupervised 
                project_description: Develop unsupervised human behaviour and affect based threat predcition model. Consists of three phases.
                project_url: https://github.com/ConSurv
                visibility: true
              - project_thumbnail: WSO2IS.png
                project_title: WSO2 IS Support for OIDC Client Initiated Back-channel Authentication(CIBA)
                project_description: Develop feature suport for WSO2 Identity Server to cater OIDC CIBA flow
                project_url: https://github.com/wso2-extensions/identity-inbound-auth-oauth/tree/master/components/org.wso2.carbon.identity.oauth.ciba
                visibility: true
#               - project_thumbnail: hack4r.PNG
#                 project_title: Hack4r
#                 project_description: A Platform built for Hackers and Penetration Testers
#                 project_url: https://hack4r.com
#                 visibility: true

# social links
twitter_username: CVinushanth
github_username:  VivekVinushanth
# facebook_username: johndoe
linkedin_username: vivek-vinushanth-christopher
# behance_username: johndoe
# instagram_username: johndoe
medium_username: vivekc.16
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: vivekc.16@cse.mrt.ac.lk

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
#  - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
